### ISSUE TITLE
Implement Create Status in mockup

### ISSUE THREAD

**Issue by danillouz** [jobstatus/web-client#15]
Shall we add a create flow to make the mockup more complete?

I was thinking to have a simple form with initially a subset of the possible fields to keep it simple. When you create you provide:

- `position`
- `company.name`
- `link`

We can default fields like:

- `status`   -> `preparing`
- `priority` -> `low`

Initially we just add the created item in memory, so we can see and better understand the workflow, required data and think more about the UX and UI.

**Comment by dinostheo** [comment]
Agreed

**Comment by danillouz** [comment]
Created a WIP PR #16 to make discussion a bit easier.
