### ISSUE TITLE
Content is lost from page when you move to mobile view

### ISSUE THREAD

**Issue by dinostheo** [jobstatus/web-client#66]
If you are typing some text in a new page on a desktop view and then you move to a mobile view, because you shrink you window, then the body and the title is lost. 
The same happens also when you move from a mobile page view to a desktop page view.

**Comment by danillouz** [comment]
Interesting bug.. 😅

In the end this is a design flaw on my end.

It's because I'm using different components based on screen size. Instead of having a single one with fluid styles. I though it was a "clever" way of circumventing my lack of CSS skills.

**Comment by danillouz** [comment]
Like discussed, I'm going to investigate if this can be solved with the feature we discussed #68

**Comment by danillouz** [comment]
This issue is fixed by #68 but the mentioned design flaw still remains. I'll make a separate issue for that.

**Comment by danillouz** [comment]
Design issue is tracked in #69
