### ISSUE TITLE
Company logos are misaligned

### ISSUE THREAD

**Issue by danillouz** [jobstatus/web-client#75]
The icon is not properly aligned with the text.

It's because we wrap it in custom components in for example the Ant list, where we should use the item meta component instead.

Also, what do you think instead of having a table/list view for the companies, we render a grid of cards, like it's done now in the company details.
I think it would be a nicer way to display the data, because I think we'd initially not have a lot of meta data to show for a company.

**Comment by dinostheo** [comment]
I think it might be nicer indeed. Also for potential search results as well. 
However, the benefit of the a table or a list at the moment is the "free" frontend pagination that we get with ant design.

**Comment by danillouz** [comment]
I can check if you can still have pagination with the grid.

Shall I have a stab at it? Or would you like to pick this up?
